### ISSUE TITLE
YAML is terrible and should be driven from the face of the Earth. 

### ISSUE THREAD

**Issue by bf4** [markbates/configatron#48]
I'd like to hear more about this. [I'm giving a talk on YAML](railsisrael2013.events.co.il/presentations/868-yaml-what-is-it-good-for) later in the year and am very interested in hearing more (of the growing number of) opinions moving away from YAML. 

We could chat here or elsewhere, if you're up for it.

**Comment by lrascao** [comment]
Google sent me here. 8 years have passed, did you end up doubling down on yaml?
