### ISSUE TITLE
How to properly reload all settings?

### ISSUE THREAD

**Issue by konung** [markbates/configatron#90]
### Scenario

I have a Setting model  where I keep some settings, that can be changed occasionally

````ruby
class CreateSettings < ActiveRecord::Migration
  def change
    create_table :settings do |t|
      t.string   :keyname, limit: 50,    null: false, index: {unique: true}
      t.text     :value,   limit: 2000,  null: false
      t.string   :name,    limit: 50
      t.string   :description
      t.timestamps   null: false, index: true
    end
    add_index :settings, :updated_at
  end
end
````

For instance this is used to keep a list of people that should be emailed for certain things . Like accounting report. 

````ruby

# To avoid doing multiple calls to DB - I pull all settings and then pluck needed settings 
configatron.settings = Configatron::Delayed.new{Setting.all.to_a}

configatron.email.errors   = Configatron::Delayed.new{configatron.settings.find{|s| s.keyname == 'email_errors_to'}.value.split(', ')}
configatron.email.accounting      = Configatron::Delayed.new{configatron.settings.find{|s| s.keyname == 'email_accounting_to'}.value.split(', ')}
configatron.email.client1_reports   = Configatron::Delayed.new{configatron.settings.find{|s| s.keyname == 'email_client1_to'}.value.split(', ')}
````

This setup works well for me.  However here every time there is a change in that record in setting ( it happens more often for several clients as people move from one department to another and don't need to be on the list anymore. ) - I need to restart the whole server - I have multiple application instances. This happens at least a couple of times a months. Often enough that's it's annoying but not often enough that I would go for  

````ruby
configatron.email.client1_reports = Configatron::Dynamic.new{Setting.where(keyname: 'email_client1_to').first.value.split(', ')}
````

 @markbates  - we actually covered this already in issue #24. And we came to a conclusion that there is no good way around it.

### Possible solution - needs feedback

I just had an idea (based on some other config settings I was coding) and wanted to run it here for feedback.

What if I was to setup
````ruby
# to be set on initially on app load 
configatron.config_last_reload_time = Time.now

configatron.config_reload = Configatron::Dynamic.new{
if configatron.config_last_reload_time > 10.minutes.ago
   configatron.config_last_reload_time = Time.now
   if st = Setting.where(keyname: 'config_reload').first.value.include?"true"
       st.value = 'false'
       st.save
       true
    else
      false
    end
else
   false
end
}

# Then
configatron.email.client1_reports = Configatron::Dynamic.new{Setting.where(keyname: 'email_client1_to').first.value.split(', ') if configatron.config_reload }

````

Then Setting.where(keyname: 'config_reload') can be set every time a user makes a setting change, but the the change won't apply for 10 minutes potentially.  And a DB will only be querried once every 10 mins, and reload all settings if reload_config got set.  This way if there is a change like this all instances of an app will get the change withing 10 minutes or less

What do you think?

**Comment by gdb** [comment]
So if I'm reading it right, you have a bug there where only the first dependent setting will actually get reloaded. That is:

1. User sets the `config_reload` flag in the DB.
2. Application hits `configatron.email.client1_reports`, and assuming it's been 10 minutes, the setting gets reloaded and the `config_reload` flag gets turned off.
3. Application hits `configatron.email.accounting`, and now the `config_reload` is already off, so no reloading happens.

I would probably recommend applying this caching idea to your original `configatron.settings` approach. That is:

- All dependent configs are Dynamics: `Configatron::Dynamic.new{configatron.settings.find{|s| s.keyname == 'email_errors_to'}.value.split(', ')}` (you could speed this up if needed by caching or making this into a hash lookup, but assuming you have few config settings it doesn't seem necessary).
- The `configatron.settings` hash is a `Configatron::Dynamic` which caches its value for 10 minutes.

Would that work for your use-case?

**Comment by gdb** [comment]
(I'm going to close this issue as having expired, please feel free to reopen it if still applicable.)
