### ISSUE TITLE
Build error after version bump

### ISSUE THREAD

**Issue by dlebauer** [markbates/configatron#91]
According to Travis, there is a build error in this repository. Not sure if I should be concerned, but it makes me think twice about using the gem that the error has been present for almost a year. 

https://travis-ci.org/markbates/configatron

**Comment by gdb** [comment]
Whoops, my mistake — thanks for the report. That was a transient build error;  I've rebuilt and it's shown as passing.

I think Mark and I consider configatron pretty stable at this point. I'm not using it anymore personally, but am still available for fixing problems if they come up.

**Comment by gdb** [comment]
(cf #92)
